/* 8x16 bitmap font with Cyrillic (sw/fw/font8x16.c, generated by sw/tools/mkfont.py). */
#ifndef FONT_H_INCLUDED
#define FONT_H_INCLUDED

#include <stdint.h>

#define FONT_W 8
#define FONT_H 16

struct font_range {
    uint16_t lo, hi, first; /* code points lo..hi -> glyphs first.. */
};

extern const struct font_range font_ranges[];
extern const uint8_t font_glyphs[][16];

/* glyph for a code point ('?' if missing) */
const uint8_t *font_glyph(uint32_t cp);
/* decode one UTF-8 character, advance *s; invalid bytes decode as '?' */
uint32_t utf8_next(const char **s);
int utf8_len(const char *s); /* characters */

#endif
