"""Generators of RTL lookup tables.

The sine ROM is emitted as a case statement in a clocked block rather than a
$readmemh file: no path resolution differences between Verilator, Gowin EDA
and yosys, and every synthesiser infers a ROM from it.

    python -m synthmodel.luts [--data-w 18] [--lut-aw 10] [-o fpga/rtl/audio/sine_quarter_rom.sv]
"""

import argparse
from pathlib import Path

from .nco import quarter_sine_table

DEFAULT_ROM = Path(__file__).resolve().parents[2] / "rtl" / "audio" / "sine_quarter_rom.sv"


def sine_rom_sv(data_w: int = 18, lut_aw: int = 10) -> str:
    table = quarter_sine_table(data_w, lut_aw)
    dw = data_w - 1
    hexw = (dw + 3) // 4
    lines = [
        "// GENERATED by fpga/model/synthmodel/luts.py -- do not edit, run `make luts`.",
        f"// Quarter-wave sine: rom[i] = round((2^{data_w - 1} - 1) * sin(pi/2 * (i + 0.5) / {1 << lut_aw})).",
        "`default_nettype none",
        "",
        "module sine_quarter_rom #(",
        f"    parameter int AW = {lut_aw},",
        f"    parameter int DW = {dw}",
        ") (",
        "    input  wire          clk,",
        "    input  wire [AW-1:0] addr,",
        "    output logic [DW-1:0] data",
        ");",
        "",
        "    // The table below is generated for fixed sizes: regenerate it rather than",
        "    // overriding the parameters (elaboration fails on a mismatch).",
        "    generate",
        f"        if (AW != {lut_aw} || DW != {dw}) begin : g_bad_params",
        "            sine_quarter_rom_regenerate_with_make_luts u_bad ();",
        "        end",
        "    endgenerate",
        "",
        "    always_ff @(posedge clk) begin",
        "        case (addr)",
    ]
    lines += [f"            {lut_aw}'d{i}: data <= {dw}'h{v:0{hexw}x};" for i, v in enumerate(table)]
    lines += [
        "            default: data <= '0;",
        "        endcase",
        "    end",
        "",
        "endmodule",
        "",
        "`default_nettype wire",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--data-w", type=int, default=18)
    p.add_argument("--lut-aw", type=int, default=10)
    p.add_argument("-o", "--out", type=Path, default=DEFAULT_ROM)
    a = p.parse_args(argv)
    a.out.write_text(sine_rom_sv(a.data_w, a.lut_aw))
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
