"""Generators of RTL lookup tables.

The sine ROM is emitted as a case statement in a clocked block rather than a
$readmemh file: no path resolution differences between Verilator, Gowin EDA
and yosys, and every synthesiser infers a ROM from it.

    python -m synthmodel.luts      (writes every file in GENERATED)
"""

import argparse
from pathlib import Path

from . import avk, pitch, softclip
from .nco import quarter_sine_table

RTL_DIR = Path(__file__).resolve().parents[2] / "rtl"
DEFAULT_ROM = RTL_DIR / "audio" / "sine_quarter_rom.sv"


def case_rom_sv(name, values, aw, dw, header):
    """Registered ROM as a case statement; parameters are checked against the table size."""
    hexw = (dw + 3) // 4
    lines = [f"// GENERATED by fpga/model/synthmodel/luts.py -- do not edit, run `make luts`."]
    lines += [f"// {h}" for h in header]
    lines += [
        "`default_nettype none",
        "",
        f"module {name} #(",
        f"    parameter int AW = {aw},",
        f"    parameter int DW = {dw}",
        ") (",
        "    input  wire          clk,",
        "    input  wire [AW-1:0] addr,",
        "    output logic [DW-1:0] data",
        ");",
        "",
        "    // The table below is generated for fixed sizes: regenerate it rather than",
        "    // overriding the parameters (elaboration fails on a mismatch).",
        "    generate",
        f"        if (AW != {aw} || DW != {dw}) begin : g_bad_params",
        f"            {name}_regenerate_with_make_luts u_bad ();",
        "        end",
        "    endgenerate",
        "",
        "    always_ff @(posedge clk) begin",
        "        case (addr)",
    ]
    lines += [f"            {aw}'d{i}: data <= {dw}'h{v:0{hexw}x};" for i, v in enumerate(values)]
    lines += ["            default: data <= '0;", "        endcase", "    end", "", "endmodule", "",
              "`default_nettype wire", ""]
    return "\n".join(lines)


def sine_rom_sv(data_w: int = 18, lut_aw: int = 10) -> str:
    return case_rom_sv(
        "sine_quarter_rom", [int(v) for v in quarter_sine_table(data_w, lut_aw)], lut_aw, data_w - 1,
        [f"Quarter-wave sine: rom[i] = round((2^{data_w - 1} - 1) * sin(pi/2 * (i + 0.5) / {1 << lut_aw}))."])


def exp_rom_sv() -> str:
    t, d = pitch.exp_table()
    assert max(d) < 256
    return case_rom_sv(
        "exp2_rom", [(dd << 18) | tt for tt, dd in zip(t, d)], pitch.EXP_AW, 26,
        ["2^x mantissa for pitch2inc: data = {D[7:0], T[17:0]},",
         "T[i] = round(2^17 * 2^(i/1024)), D[i] = T[i+1] - T[i]. Model: synthmodel/pitch.py."])


def tanh_rom_sv() -> str:
    t, d, _ = softclip.tanh_table()
    assert max(d) < 1024 and max(t) < (1 << 17)
    return case_rom_sv(
        "tanh_rom", [(dd << 17) | tt for tt, dd in zip(t, d)], 9, 27,
        ["tanh knee for softclip: data = {D[9:0], T[16:0]},",
         "T[i] = round(tanh(i/128) * 2^16), D[i] = T[i+1] - T[i]. Model: synthmodel/softclip.py."])


def fir_rom_sv() -> str:
    taps = avk.fir_taps()
    return case_rom_sv(
        "fir_rom", [t & 0x3FFFF for t in taps], 6, 18,
        [f"{avk.FIR_TAPS}-tap decimation FIR for the AVK inputs, Q1.17 two's complement.",
         "Model: synthmodel/avk.py (fir_taps)."])


GENERATED = {
    "audio/sine_quarter_rom.sv": lambda: sine_rom_sv(18, 10),
    "audio/exp2_rom.sv": exp_rom_sv,
    "audio/tanh_rom.sv": tanh_rom_sv,
    "avk/fir_rom.sv": fir_rom_sv,
}


def main(argv=None) -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.parse_args(argv)
    for rel, gen in GENERATED.items():
        (RTL_DIR / rel).write_text(gen())
        print(f"wrote {RTL_DIR / rel}")


if __name__ == "__main__":
    main()
