// GENERATED by fpga/model/synthmodel/luts.py -- do not edit, run `make luts`.
// 64-tap decimation FIR for the AVK inputs, Q1.17 two's complement.
// Model: synthmodel/avk.py (fir_taps).
`default_nettype none

module fir_rom #(
    parameter int AW = 6,
    parameter int DW = 18
) (
    input  wire          clk,
    input  wire [AW-1:0] addr,
    output logic [DW-1:0] data
);

    // The table below is generated for fixed sizes: regenerate it rather than
    // overriding the parameters (elaboration fails on a mismatch).
    generate
        if (AW != 6 || DW != 18) begin : g_bad_params
            fir_rom_regenerate_with_make_luts u_bad ();
        end
    endgenerate

    always_ff @(posedge clk) begin
        case (addr)
            6'd0: data <= 18'h00000;
            6'd1: data <= 18'h0000a;
            6'd2: data <= 18'h0001a;
            6'd3: data <= 18'h00024;
            6'd4: data <= 18'h00016;
            6'd5: data <= 18'h3ffe3;
            6'd6: data <= 18'h3ff98;
            6'd7: data <= 18'h3ff60;
            6'd8: data <= 18'h3ff76;
            6'd9: data <= 18'h3fffd;
            6'd10: data <= 18'h000dd;
            6'd11: data <= 18'h001ad;
            6'd12: data <= 18'h001d7;
            6'd13: data <= 18'h000e9;
            6'd14: data <= 18'h3fef3;
            6'd15: data <= 18'h3fcb8;
            6'd16: data <= 18'h3fb7f;
            6'd17: data <= 18'h3fc77;
            6'd18: data <= 18'h3fff5;
            6'd19: data <= 18'h004e5;
            6'd20: data <= 18'h008ed;
            6'd21: data <= 18'h00951;
            6'd22: data <= 18'h00466;
            6'd23: data <= 18'h3fae7;
            6'd24: data <= 18'h3f069;
            6'd25: data <= 18'h3ea82;
            6'd26: data <= 18'h3eeb3;
            6'd27: data <= 18'h3ffec;
            6'd28: data <= 18'h01cb1;
            6'd29: data <= 18'h03ee2;
            6'd30: data <= 18'h05d71;
            6'd31: data <= 18'h06f76;
            6'd32: data <= 18'h06f76;
            6'd33: data <= 18'h05d71;
            6'd34: data <= 18'h03ee2;
            6'd35: data <= 18'h01cb1;
            6'd36: data <= 18'h3ffec;
            6'd37: data <= 18'h3eeb3;
            6'd38: data <= 18'h3ea82;
            6'd39: data <= 18'h3f069;
            6'd40: data <= 18'h3fae7;
            6'd41: data <= 18'h00466;
            6'd42: data <= 18'h00951;
            6'd43: data <= 18'h008ed;
            6'd44: data <= 18'h004e5;
            6'd45: data <= 18'h3fff5;
            6'd46: data <= 18'h3fc77;
            6'd47: data <= 18'h3fb7f;
            6'd48: data <= 18'h3fcb8;
            6'd49: data <= 18'h3fef3;
            6'd50: data <= 18'h000e9;
            6'd51: data <= 18'h001d7;
            6'd52: data <= 18'h001ad;
            6'd53: data <= 18'h000dd;
            6'd54: data <= 18'h3fffd;
            6'd55: data <= 18'h3ff76;
            6'd56: data <= 18'h3ff60;
            6'd57: data <= 18'h3ff98;
            6'd58: data <= 18'h3ffe3;
            6'd59: data <= 18'h00016;
            6'd60: data <= 18'h00024;
            6'd61: data <= 18'h0001a;
            6'd62: data <= 18'h0000a;
            6'd63: data <= 18'h00000;
            default: data <= '0;
        endcase
    end

endmodule

`default_nettype wire
