# Portable RTL, paths relative to fpga/rtl. Used by the Makefile / tests (Verilator)
# and by fpga/boards/*/build.tcl (Gowin EDA).
common/sync_fifo.sv
audio/sine_quarter_rom.sv
audio/exp2_rom.sv
audio/audio_clkgen.sv
audio/i2s_tx.sv
audio/nco_sine.sv
audio/pitch2inc.sv
audio/dac_scale.sv
audio/tanh_rom.sv
audio/softclip.sv
voice/voice_engine.sv
voice/mod_unit.sv
midi/uart_rx.sv
midi/uart_tx.sv
midi/midi_parser.sv
third_party/picorv32/picorv32.v
soc/boot_rom.sv
soc/soc_ram.sv
soc/spi_master.sv
soc/periph_uart.sv
soc/periph_timer.sv
soc/periph_gpio.sv
soc/periph_midi.sv
panel/periph_pots.sv
panel/periph_enc.sv
panel/lcd_ctrl.sv
stub_core.sv
mono_core.sv
synth_core.sv
