#!/usr/bin/env python3
"""Generate sw/fw/font8x16.c: 8x16 bitmap glyphs (ASCII, Cyrillic, a few symbols) from GNU Unifont.

GNU Unifont 13.0.04+ is dual-licensed: GPLv2+ with the GNU font embedding exception, or SIL OFL 1.1.
Needs Pillow and unifont.otf (Debian/Ubuntu package fonts-unifont).

    python3 sw/tools/mkfont.py [--font /usr/share/fonts/opentype/unifont/unifont.otf]
"""

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

RANGES = [
    (0x20, 0x7E),      # ASCII
    (0xB0, 0xB0),      # degree
    (0x401, 0x401),    # Ё
    (0x410, 0x44F),    # А..я
    (0x451, 0x451),    # ё
    (0x2190, 0x2193),  # arrows
]
OUT = Path(__file__).resolve().parents[1] / "fw" / "font8x16.c"


def glyph(font, cp):
    im = Image.new("1", (8, 16), 0)
    ImageDraw.Draw(im).text((0, 0), chr(cp), font=font, fill=1)
    return [sum(im.getpixel((x, y)) << (7 - x) for x in range(8)) for y in range(16)]


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--font", default="/usr/share/fonts/opentype/unifont/unifont.otf")
    a = p.parse_args()
    font = ImageFont.truetype(a.font, 16)
    lines = [
        "/* GENERATED by sw/tools/mkfont.py -- do not edit.",
        " * 8x16 glyphs from GNU Unifont (GPLv2+ with the font embedding exception / SIL OFL 1.1).",
        " * One byte per row, MSB = leftmost pixel. */",
        '#include "font.h"',
        "",
        "const struct font_range font_ranges[] = {",
    ]
    first = 0
    for lo, hi in RANGES:
        lines.append(f"    {{0x{lo:04X}, 0x{hi:04X}, {first}}},")
        first += hi - lo + 1
    lines += ["    {0, 0, 0},", "};", "", f"const uint8_t font_glyphs[{first}][16] = {{"]
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            rows = ", ".join(f"0x{b:02X}" for b in glyph(font, cp))
            lines.append(f"    {{{rows}}}, /* U+{cp:04X} */")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {first} glyphs")


if __name__ == "__main__":
    main()
